"""
Contract generator — creates licensing agreements from deal terms.

Generates contract text from templates with deal-specific merge fields.
Templates are placeholders for legal counsel to refine.
Supports PDF output via fpdf2.
"""

import io
import logging
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from ..config import get_settings

logger = logging.getLogger(__name__)
_settings = get_settings()


def text_to_pdf(title: str, text: str) -> bytes:
    """Convert contract text to a formatted PDF document.

    Returns PDF bytes ready to be stored or sent as a response.
    """
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(6)

        # Body
        pdf.set_font("Helvetica", "", 10)
        for line in text.split("\n"):
            line = line.strip()
            if not line:
                pdf.ln(4)
                continue
            # Section headers (all caps or start with number + period)
            if line.isupper() or (len(line) > 2 and line[0].isdigit() and line[1] == '.'):
                pdf.set_font("Helvetica", "B", 11)
                pdf.ln(4)
                pdf.multi_cell(0, 6, line)
                pdf.set_font("Helvetica", "", 10)
            else:
                pdf.multi_cell(0, 5, line)

        # Footer
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 5, f"Generated by AIV Platform | {datetime.now(timezone.utc).strftime('%B %d, %Y')}", align="C")

        return pdf.output()
    except ImportError:
        logger.warning("fpdf2 not installed — returning text as bytes")
        return text.encode("utf-8")


def generate_licensing_agreement(
    twin_name: str,
    twin_category: str,
    client_org_name: str,
    deal_type: str,
    deal_value: float,
    currency: str,
    territory: list,
    data_scope: list,
    exclusivity: bool,
    commission_rate: float,
    deal_number: int,
) -> str:
    """Generate a licensing agreement from deal terms.

    This is a placeholder template. Legal counsel should review and refine
    the actual agreement text before production use.
    """
    territory_str = ", ".join(territory) if territory else "Worldwide"
    scope_str = ", ".join([s.replace("_", " ").title() for s in data_scope]) if data_scope else "Full Identity Package"
    exclusivity_str = "Exclusive" if exclusivity else "Non-Exclusive"
    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")

    return f"""AIV IDENTITY LICENSING AGREEMENT

Date: {date_str}
Agreement Number: AIV-LA-{deal_number:04d}

PARTIES

Licensor: {twin_name} (via AIV Platform)
Identity Category: {twin_category}

Licensee: {client_org_name}

TERMS

1. GRANT OF LICENSE
   Licensor grants Licensee a {exclusivity_str.lower()} license to use the
   identity data specified in the Data Scope below, subject to the terms
   and conditions of this Agreement.

2. DATA SCOPE
   The following identity modules are included in this license:
   {scope_str}

3. TERRITORY
   This license is valid in the following territories:
   {territory_str}

4. DEAL VALUE AND PAYMENT
   Total License Fee: {currency} {deal_value:,.2f}
   Payment Terms: Net 30 from execution date

5. COMMISSION
   AIV Platform Commission: {commission_rate * 100:.0f}% of gross deal value
   Commission Amount: {currency} {deal_value * commission_rate:,.2f}
   Net to Licensor: {currency} {deal_value * (1 - commission_rate):,.2f}

6. EXCLUSIVITY
   This license is granted on a {exclusivity_str.upper()} basis.
   {"No other party may be granted rights to the same data scope in the same territory during the term of this agreement." if exclusivity else "Licensor retains the right to grant similar licenses to other parties."}

7. DATA HANDLING
   Licensee agrees to:
   a) Use the licensed data only for the purposes stated in this agreement
   b) Not sublicense, share, or transfer the data to third parties without written consent
   c) Comply with all applicable data protection regulations (GDPR, CCPA)
   d) Destroy all copies of the data upon agreement termination
   e) Submit Permitted Use Lifecycle (PUL) attestations as required

8. GUARDRAILS
   Licensee shall comply with all behavioral guardrails established by the Licensor
   on the AIV Platform. Content generated using the licensed data must adhere to
   these guardrails at all times.

9. IDENTITY VERIFICATION
   All outputs produced using this licensed data carry AIV identity verification
   metadata (AIV Seal) confirming authorized use and provenance.

10. TERM AND TERMINATION
    This agreement becomes effective upon execution by both parties and
    remains in effect for the duration specified in the deal terms,
    unless terminated earlier by either party with 30 days written notice.

11. GOVERNING LAW
    This agreement shall be governed by and construed in accordance with
    the laws of the State of Delaware, United States.

12. ENTIRE AGREEMENT
    This agreement, together with the Platform Services Agreement and any
    applicable Reference Data Agreements, constitutes the entire agreement
    between the parties.

SIGNATURES

Licensor (or authorized representative):
Name: ________________________
Date: ________________________
Signature: ________________________

Licensee:
Name: ________________________
Date: ________________________
Signature: ________________________

---
Generated by AIV Platform
This is a template agreement. Legal counsel should review before execution.
"""


def generate_platform_services_agreement(
    user_name: str,
    org_name: str,
    role: str,
) -> str:
    """Generate the Platform Services Agreement (PSA) template.

    Signed during onboarding. Covers the relationship between AIV and
    the talent/manager/organization.
    """
    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")

    return f"""AIV PLATFORM SERVICES AGREEMENT

Date: {date_str}

PARTIES

Service Provider: AIV, Inc. ("AIV")
Client: {user_name}, {org_name} ("Client")
Role: {role.title()}

1. SERVICES
   AIV provides identity infrastructure services including:
   a) Digital identity capture, structuring, and validation
   b) Identity protection and monitoring
   c) Licensing portal and deal management
   d) AI training and refinement tools
   e) Cryptographic identity verification (AIV Seal)
   f) Blockchain-anchored proof of ownership

2. COMMISSION STRUCTURE
   AIV retains a commission on each licensing deal:
   - First deal: {int(_settings.commission_rate_first_deal * 100)}% of gross deal value
   - Second deal: {int(_settings.commission_rate_second_deal * 100)}% of gross deal value
   - Third deal and beyond: {int(_settings.commission_rate_default * 100)}% of gross deal value

3. PLATFORM PARTNERSHIP FEE
   A monthly fee of ${int(_settings.platform_fee_monthly):,} USD activates when:
   - The first licensing deal is executed, OR
   - 90 days after onboarding completion
   Whichever occurs first. This fee covers ongoing AI training,
   identity hosting, licensing operations, misuse monitoring,
   and account management.

4. DATA OWNERSHIP
   Client retains full ownership of their identity data at all times.
   AIV acts as a data processor, not a data owner. Client may request
   full data export or deletion at any time, subject to active deal
   obligations.

5. DEPARTURE TERMS
   Client may terminate this agreement with 30 days written notice.
   Upon termination:
   a) Active deals continue until their natural conclusion
   b) Commission obligations on active deals remain
   c) Platform fee ceases at end of current billing period
   d) Identity data is exported or deleted per Client's request
   e) Blockchain seals remain immutable (cannot be removed)

6. LIABILITY
   AIV shall not be liable for any indirect, incidental, or
   consequential damages arising from the use of the platform.
   Total liability is limited to fees paid in the preceding 12 months.

7. DISPUTE RESOLUTION
   Any disputes shall be resolved through binding arbitration
   in the State of Delaware, United States.

8. CONFIDENTIALITY
   Both parties agree to maintain confidentiality of all proprietary
   information shared during the course of this agreement.

ACCEPTANCE

By using the AIV platform and completing the onboarding process,
Client agrees to the terms of this Platform Services Agreement.

---
Generated by AIV Platform
This is a template agreement. Legal counsel should review before execution.
"""


def generate_data_processing_agreement(
    user_name: str,
    org_name: str,
) -> str:
    """Generate the Data Processing Agreement (DPA) template.

    GDPR/CCPA compliance. Signed during onboarding.
    """
    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")

    return f"""AIV DATA PROCESSING AGREEMENT

Date: {date_str}

DATA CONTROLLER: {user_name}, {org_name}
DATA PROCESSOR: AIV, Inc.

1. PURPOSE
   This agreement governs the processing of personal data by AIV
   on behalf of the Data Controller for the purpose of digital
   identity management and licensing.

2. DATA PROCESSED
   - Biographical information (name, occupation, public history)
   - Voice samples and vocal characteristics
   - Behavioral patterns and communication style
   - Visual likeness data (photographs, video)
   - Public social media content (with consent)

3. PROCESSING ACTIVITIES
   - Psychographic classification and dimensional scoring
   - Personality modeling and behavioral analysis
   - Voice synthesis preparation
   - Identity verification and blockchain anchoring
   - Licensing package assembly and delivery

4. DATA SECURITY
   AIV implements industry-standard security measures including:
   - AES-256 encryption for identity data at rest
   - TLS 1.3 for data in transit
   - Per-user encryption keys for identity core data
   - Access logging on all data operations
   - Regular security audits

5. DATA RETENTION
   - Active data: retained while agreement is in effect
   - Audit logs: retained for 7 years (legal requirement)
   - Blockchain records: immutable and permanent
   - Upon termination: personal data deleted within 30 days,
     except as required by law or active deal obligations

6. DATA SUBJECT RIGHTS
   Data Controller may exercise the following rights:
   - Access: request a copy of all processed data
   - Rectification: correct inaccurate data
   - Erasure: request deletion (subject to legal obligations)
   - Portability: receive data in machine-readable format
   - Restriction: limit processing scope

7. SUB-PROCESSORS
   AIV may engage sub-processors for specific functions:
   - Cloud infrastructure (AWS/GCP)
   - Payment processing (Stripe)
   - Email delivery (Resend)
   - Blockchain anchoring (Polygon network)
   Data Controller will be notified of sub-processor changes.

8. BREACH NOTIFICATION
   In the event of a data breach, AIV will notify the Data Controller
   within 72 hours of becoming aware of the breach.

---
Generated by AIV Platform
This is a template agreement. Legal counsel should review before execution.
"""
