import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID

from ..database import Base


class AccessCode(Base):
    """Access codes for invite-only registration.

    Generated by admins or relationship anchors. Each code can be used once.
    Format: AIV-XXXXXX (6 alphanumeric characters).
    """

    __tablename__ = "access_codes"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    code = Column(String(20), unique=True, nullable=False, index=True)
    label = Column(String(255), nullable=True)  # e.g. "Investor - John", "Beta Talent"
    is_used = Column(Boolean, default=False, nullable=False)
    used_by = Column(UUID(as_uuid=True), ForeignKey("user_table.id"), nullable=True)
    used_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    expires_at = Column(DateTime(timezone=True), nullable=True)
