"""phase2_new_platform_schema_31_tables

Revision ID: 572ffe12d7dd
Revises: 20260314_add_bc_fields
Create Date: 2026-03-20 22:06:14.520179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '572ffe12d7dd'
down_revision: Union[str, None] = '20260314_add_bc_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id')
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=True),
    sa.Column('current_mode', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_twin_id'), 'consent_records', ['twin_id'], unique=False)
    op.create_table('guardrail_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configured_by', sa.UUID(), nullable=False),
    sa.Column('blocked_topics', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('restricted_topics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('language_restrictions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('min_formality', sa.Integer(), nullable=True),
    sa.Column('max_controversy', sa.Integer(), nullable=True),
    sa.Column('humor_permitted', sa.Boolean(), nullable=True),
    sa.Column('humor_blacklist', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('require_ai_disclosure', sa.Boolean(), nullable=True),
    sa.Column('disclosure_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['configured_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_package_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('alcm_snapshot_ref', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('change_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('seal_id', sa.UUID(), nullable=False),
    sa.Column('seal_hash', sa.String(length=128), nullable=False),
    sa.Column('seal_generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tx_hash', sa.String(length=70), nullable=True),
    sa.Column('block_number', sa.String(length=20), nullable=True),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('cascaded_to_deals', sa.Integer(), nullable=True),
    sa.Column('cascade_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twin_id', 'version_number')
    )
    op.create_table('licensing_rules_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configured_by', sa.UUID(), nullable=False),
    sa.Column('pricing_floor', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('territory_restrictions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('blacklisted_use_cases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('permitted_use_cases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('exclusivity_available', sa.Boolean(), nullable=True),
    sa.Column('auto_approve_threshold', sa.Float(), nullable=True),
    sa.Column('escalate_below', sa.Float(), nullable=True),
    sa.Column('block_below', sa.Float(), nullable=True),
    sa.Column('default_grace_period_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['configured_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('available_use_cases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('available_territories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('pricing_guidance', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twin_id')
    )
    op.create_table('misuse_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('detection_type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enforcement_action', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('contributor_type', sa.String(length=50), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('agent_mode', sa.String(length=50), nullable=True),
    sa.Column('alcm_processing_status', sa.String(length=50), nullable=True),
    sa.Column('alcm_processing_result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['contributor_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_contributions_approval_status'), 'training_contributions', ['approval_status'], unique=False)
    op.create_index(op.f('ix_training_contributions_twin_id'), 'training_contributions', ['twin_id'], unique=False)
    op.create_table('twin_locks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('lock_scope', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reinstated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reinstated_by', sa.UUID(), nullable=True),
    sa.Column('reinstatement_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reinstated_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('mode_at_time', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    op.create_table('client_validation_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('sample_content', sa.Text(), nullable=False),
    sa.Column('sample_context', sa.Text(), nullable=True),
    sa.Column('sample_modality', sa.String(length=20), nullable=True),
    sa.Column('personality_consistency', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('inconsistency_details', sa.Text(), nullable=True),
    sa.Column('talent_review_status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contract_url', sa.Text(), nullable=False),
    sa.Column('signed_by_talent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_client_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('esignature_ref', sa.Text(), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=True),
    sa.Column('parent_contract_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['parent_contract_id'], ['deal_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_contracts_deal_id'), 'deal_contracts', ['deal_id'], unique=False)
    op.create_table('deal_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_messages_deal_id'), 'deal_messages', ['deal_id'], unique=False)
    op.create_table('deal_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_milestones_deal_id'), 'deal_milestones', ['deal_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('client_organization_id', sa.UUID(), nullable=False),
    sa.Column('use_case', sa.Text(), nullable=False),
    sa.Column('territory', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('converted_deal_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_organization_id'], ['organization_table.id'], ),
    sa.ForeignKeyConstraint(['converted_deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiation_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('knowledge_type', sa.String(length=50), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_knowledge_twin_id'), 'negotiation_knowledge', ['twin_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(), nullable=False),
    sa.Column('commission_amount', sa.Numeric(), nullable=False),
    sa.Column('net_amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permitted_use_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('content_produced', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('platforms_used', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('territories_reached', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('production_partners', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_tools_used', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('scope_changes', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permitted_use_records_deal_id'), 'permitted_use_records', ['deal_id'], unique=False)
    op.create_table('reference_data_agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('data_manifest', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('recipient_org', sa.Text(), nullable=False),
    sa.Column('recipient_contact', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('restrictions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('destruction_required_by', sa.Date(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_confirmed', sa.Boolean(), nullable=True),
    sa.Column('destruction_confirmed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_partner_disclosures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('rda_id', sa.UUID(), nullable=True),
    sa.Column('partner_name', sa.Text(), nullable=False),
    sa.Column('partner_role', sa.Text(), nullable=False),
    sa.Column('partner_contact', sa.Text(), nullable=True),
    sa.Column('data_access_scope', sa.Text(), nullable=True),
    sa.Column('disclosed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['rda_id'], ['reference_data_agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_meters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('twin_id', sa.UUID(), nullable=True),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit_rate', sa.Numeric(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_table.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_logs', sa.Column('actor_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_type', sa.String(length=50), nullable=False, server_default='SYSTEM'))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'user_table', ['actor_id'], ['id'])
    op.drop_column('audit_logs', 'user_id')
    op.add_column('deals', sa.Column('client_organization_id', sa.UUID(), nullable=True))
    op.add_column('deals', sa.Column('deal_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('deals', sa.Column('commission_rate', sa.Numeric(), nullable=False, server_default='0.30'))
    op.add_column('deals', sa.Column('commission_amount', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('deals', sa.Column('territory', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('deals', sa.Column('exclusivity', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('data_scope', postgresql.ARRAY(sa.Text()), nullable=False, server_default='{}'))
    op.add_column('deals', sa.Column('package_version_at_exec', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('version_hold_requested', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('version_hold_approved', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('grace_period_hours', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('deals', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deals', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('deals', 'deal_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('deals', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               nullable=False)
    op.alter_column('deals', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               nullable=True)
    op.alter_column('deals', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('deals', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('deals', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'NEGOTIATION', 'CONTRACT_SENT', 'ACTIVE', 'COMPLETED', 'EXPIRED', name='dealstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('deals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_deals_client_organization_id'), 'deals', ['client_organization_id'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_unique_constraint(None, 'deals', ['twin_id', 'deal_number'])
    op.create_foreign_key(None, 'deals', 'organization_table', ['client_organization_id'], ['id'])
    op.create_foreign_key(None, 'deals', 'user_table', ['approved_by'], ['id'])
    op.drop_column('deals', 'notes')
    op.drop_column('deals', 'brand_name')
    op.drop_column('deals', 'document_ids')
    op.add_column('onboarding_sessions', sa.Column('initiated_by', sa.UUID(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('onboarding_path', sa.String(length=50), nullable=False, server_default='HYBRID'))
    op.add_column('onboarding_sessions', sa.Column('discovery_input', sa.Text(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('discovered_profiles', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('wikipedia_url', sa.Text(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('discovery_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('consent_public_scraping', sa.Boolean(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('consent_granted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('identity_verification', sa.String(length=50), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('identity_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('uploaded_file_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('files_processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('gate_1_manager_approved', sa.Boolean(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('gate_1_approved_by', sa.UUID(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('gate_1_approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('gate_2_talent_authorized', sa.Boolean(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('gate_2_authorized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('onboarding_sessions', 'status',
               existing_type=postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='onboardingstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_onboarding_sessions_twin_id', table_name='onboarding_sessions')
    op.drop_index('ix_onboarding_sessions_user_id', table_name='onboarding_sessions')
    op.drop_constraint('onboarding_sessions_user_id_fkey', 'onboarding_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_sessions', 'user_table', ['gate_1_approved_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_sessions', 'user_table', ['initiated_by'], ['id'])
    op.drop_column('onboarding_sessions', 'user_id')
    op.drop_column('onboarding_sessions', 'current_step')
    op.drop_column('onboarding_sessions', 'started_at')
    op.drop_column('onboarding_sessions', 'user_responses')
    op.drop_column('onboarding_sessions', 'conversation_history')
    op.drop_column('onboarding_sessions', 'voice_sample_urls')
    op.drop_column('onboarding_sessions', 'research_data')
    op.add_column('organization_table', sa.Column('type', sa.String(length=50), nullable=False, server_default='TALENT_TEAM'))
    op.add_column('twins', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('twins', sa.Column('talent_user_id', sa.UUID(), nullable=True))
    op.add_column('twins', sa.Column('alcm_twin_id', sa.UUID(), nullable=True))
    op.add_column('twins', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('twins', sa.Column('identity_category', sa.String(length=50), nullable=True))
    op.add_column('twins', sa.Column('identity_category_secondary', sa.String(length=50), nullable=True))
    op.add_column('twins', sa.Column('clone_type', sa.String(length=50), nullable=True))
    op.add_column('twins', sa.Column('stage_1_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('twins', sa.Column('stage_2_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('twins', sa.Column('fee_free_window_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('twins', sa.Column('platform_fee_active', sa.Boolean(), nullable=True))
    op.add_column('twins', sa.Column('health_status', sa.String(length=50), nullable=True))
    op.add_column('twins', sa.Column('health_last_computed', sa.DateTime(timezone=True), nullable=True))
    op.add_column('twins', sa.Column('last_training_activity', sa.DateTime(timezone=True), nullable=True))
    op.add_column('twins', sa.Column('last_quarterly_audit', sa.DateTime(timezone=True), nullable=True))
    op.add_column('twins', sa.Column('next_quarterly_audit', sa.DateTime(timezone=True), nullable=True))
    op.add_column('twins', sa.Column('successor_contact_email', sa.String(length=255), nullable=True))
    op.add_column('twins', sa.Column('successor_contact_name', sa.String(length=255), nullable=True))
    op.add_column('twins', sa.Column('successor_designated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('twins', sa.Column('talent_authorization_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('twins', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'CERTIFIED', 'SUSPENDED', name='twinstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_twins_user_id', table_name='twins')
    op.create_index(op.f('ix_twins_organization_id'), 'twins', ['organization_id'], unique=False)
    op.create_index(op.f('ix_twins_talent_user_id'), 'twins', ['talent_user_id'], unique=False)
    op.drop_constraint('twins_user_id_fkey', 'twins', type_='foreignkey')
    op.create_foreign_key(None, 'twins', 'user_table', ['talent_user_id'], ['id'])
    op.create_foreign_key(None, 'twins', 'organization_table', ['organization_id'], ['id'])
    op.drop_column('twins', 'user_id')
    op.drop_column('twins', 'category')
    op.drop_column('twins', 'version')
    op.drop_column('twins', 'alcm_data')
    op.drop_column('twins', 'completeness_score')
    op.drop_column('twins', 'governance')
    op.drop_column('twins', 'voice_status')
    op.drop_column('twins', 'voice_id')
    op.drop_column('twins', 'commercial_terms')
    op.drop_column('twins', 'voice_sample_url')
    op.drop_column('twins', 'name')
    op.add_column('user_table', sa.Column('role', sa.String(length=50), nullable=False, server_default='TALENT'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'role')
    op.add_column('twins', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('twins', sa.Column('voice_sample_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('twins', sa.Column('commercial_terms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('twins', sa.Column('voice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('twins', sa.Column('voice_status', postgresql.ENUM('PENDING', 'PROCESSING', 'READY', 'FAILED', name='voicestatus'), autoincrement=False, nullable=False))
    op.add_column('twins', sa.Column('governance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('twins', sa.Column('completeness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('twins', sa.Column('alcm_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('twins', sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('twins', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('twins', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'twins', type_='foreignkey')
    op.drop_constraint(None, 'twins', type_='foreignkey')
    op.create_foreign_key('twins_user_id_fkey', 'twins', 'user_table', ['user_id'], ['id'])
    op.drop_index(op.f('ix_twins_talent_user_id'), table_name='twins')
    op.drop_index(op.f('ix_twins_organization_id'), table_name='twins')
    op.create_index('ix_twins_user_id', 'twins', ['user_id'], unique=False)
    op.alter_column('twins', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('DRAFT', 'ACTIVE', 'CERTIFIED', 'SUSPENDED', name='twinstatus'),
               existing_nullable=False)
    op.drop_column('twins', 'talent_authorization_at')
    op.drop_column('twins', 'successor_designated_at')
    op.drop_column('twins', 'successor_contact_name')
    op.drop_column('twins', 'successor_contact_email')
    op.drop_column('twins', 'next_quarterly_audit')
    op.drop_column('twins', 'last_quarterly_audit')
    op.drop_column('twins', 'last_training_activity')
    op.drop_column('twins', 'health_last_computed')
    op.drop_column('twins', 'health_status')
    op.drop_column('twins', 'platform_fee_active')
    op.drop_column('twins', 'fee_free_window_expires')
    op.drop_column('twins', 'stage_2_completed_at')
    op.drop_column('twins', 'stage_1_completed_at')
    op.drop_column('twins', 'clone_type')
    op.drop_column('twins', 'identity_category_secondary')
    op.drop_column('twins', 'identity_category')
    op.drop_column('twins', 'display_name')
    op.drop_column('twins', 'alcm_twin_id')
    op.drop_column('twins', 'talent_user_id')
    op.drop_column('twins', 'organization_id')
    op.drop_column('organization_table', 'type')
    op.add_column('onboarding_sessions', sa.Column('research_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('onboarding_sessions', sa.Column('voice_sample_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('onboarding_sessions', sa.Column('conversation_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('onboarding_sessions', sa.Column('user_responses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('onboarding_sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('onboarding_sessions', sa.Column('current_step', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('onboarding_sessions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'onboarding_sessions', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_sessions', type_='foreignkey')
    op.create_foreign_key('onboarding_sessions_user_id_fkey', 'onboarding_sessions', 'user_table', ['user_id'], ['id'])
    op.create_index('ix_onboarding_sessions_user_id', 'onboarding_sessions', ['user_id'], unique=False)
    op.create_index('ix_onboarding_sessions_twin_id', 'onboarding_sessions', ['twin_id'], unique=False)
    op.alter_column('onboarding_sessions', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='onboardingstatus'),
               existing_nullable=False)
    op.drop_column('onboarding_sessions', 'created_at')
    op.drop_column('onboarding_sessions', 'gate_2_authorized_at')
    op.drop_column('onboarding_sessions', 'gate_2_talent_authorized')
    op.drop_column('onboarding_sessions', 'gate_1_approved_at')
    op.drop_column('onboarding_sessions', 'gate_1_approved_by')
    op.drop_column('onboarding_sessions', 'gate_1_manager_approved')
    op.drop_column('onboarding_sessions', 'files_processed_at')
    op.drop_column('onboarding_sessions', 'uploaded_file_urls')
    op.drop_column('onboarding_sessions', 'identity_verified_at')
    op.drop_column('onboarding_sessions', 'identity_verification')
    op.drop_column('onboarding_sessions', 'consent_granted_at')
    op.drop_column('onboarding_sessions', 'consent_public_scraping')
    op.drop_column('onboarding_sessions', 'discovery_completed_at')
    op.drop_column('onboarding_sessions', 'wikipedia_url')
    op.drop_column('onboarding_sessions', 'discovered_profiles')
    op.drop_column('onboarding_sessions', 'discovery_input')
    op.drop_column('onboarding_sessions', 'onboarding_path')
    op.drop_column('onboarding_sessions', 'initiated_by')
    op.add_column('deals', sa.Column('document_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('brand_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='unique')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_client_organization_id'), table_name='deals')
    op.alter_column('deals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deals', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('DRAFT', 'NEGOTIATION', 'CONTRACT_SENT', 'ACTIVE', 'COMPLETED', 'EXPIRED', name='dealstatus'),
               existing_nullable=False)
    op.alter_column('deals', 'end_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('deals', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('deals', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('deals', 'value',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('deals', 'deal_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('deals', 'completed_at')
    op.drop_column('deals', 'executed_at')
    op.drop_column('deals', 'approved_by')
    op.drop_column('deals', 'grace_period_hours')
    op.drop_column('deals', 'version_hold_approved')
    op.drop_column('deals', 'version_hold_requested')
    op.drop_column('deals', 'package_version_at_exec')
    op.drop_column('deals', 'data_scope')
    op.drop_column('deals', 'exclusivity')
    op.drop_column('deals', 'territory')
    op.drop_column('deals', 'commission_amount')
    op.drop_column('deals', 'commission_rate')
    op.drop_column('deals', 'deal_number')
    op.drop_column('deals', 'client_organization_id')
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'user_table', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('audit_logs', 'actor_type')
    op.drop_column('audit_logs', 'actor_id')
    op.drop_table('usage_meters')
    op.drop_table('production_partner_disclosures')
    op.drop_table('reference_data_agreements')
    op.drop_index(op.f('ix_permitted_use_records_deal_id'), table_name='permitted_use_records')
    op.drop_table('permitted_use_records')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_negotiation_knowledge_twin_id'), table_name='negotiation_knowledge')
    op.drop_table('negotiation_knowledge')
    op.drop_table('marketplace_inquiries')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_deal_milestones_deal_id'), table_name='deal_milestones')
    op.drop_table('deal_milestones')
    op.drop_index(op.f('ix_deal_messages_deal_id'), table_name='deal_messages')
    op.drop_table('deal_messages')
    op.drop_index(op.f('ix_deal_contracts_deal_id'), table_name='deal_contracts')
    op.drop_table('deal_contracts')
    op.drop_table('client_validation_submissions')
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_table('twin_locks')
    op.drop_index(op.f('ix_training_contributions_twin_id'), table_name='training_contributions')
    op.drop_index(op.f('ix_training_contributions_approval_status'), table_name='training_contributions')
    op.drop_table('training_contributions')
    op.drop_table('misuse_detections')
    op.drop_table('marketplace_listings')
    op.drop_table('licensing_rules_configs')
    op.drop_table('identity_package_versions')
    op.drop_table('guardrail_configs')
    op.drop_index(op.f('ix_consent_records_twin_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
